name: Build staging image
on:
  push:
    branches:
      - main

jobs:
  detect-changes:
    uses: ./.github/workflows/detect-changes.yml
  get-tags-reports:
    needs: detect-changes
    if: needs.detect-changes.outputs.reports-api == 'true'
    uses: ./.github/workflows/get-staging-tags.yml
    with:
      package: reports
  build-and-push-reports:
    needs: get-tags-reports
    uses: ./.github/workflows/build-template.yml
    with:
      tags: ${{ needs.get-tags-reports.outputs.tags }}
      package: reports
    secrets:
      PUBLISH_IMAGE_TOKEN: ${{ secrets.PUBLISH_IMAGE_TOKEN }}
  get-tags-users:
    needs: detect-changes
    if: needs.detect-changes.outputs.users-api == 'true'
    uses: ./.github/workflows/get-staging-tags.yml
    with:
      package: users
  build-and-push-users:
    needs: get-tags-users
    uses: ./.github/workflows/build-template.yml
    with:
      tags: ${{ needs.get-tags-users.outputs.tags }}
      package: users
    secrets:
      PUBLISH_IMAGE_TOKEN: ${{ secrets.PUBLISH_IMAGE_TOKEN }}
