name: CI
on:
  pull_request:
    branches:
      - main
    paths:
      - 'libs/**'
      - 'reports/**'

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Set up Poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: '1.3.1'
      - name: Detect changes
        uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            reports-api:
              - 'reports/**'
              - 'libs/**'
            db-handler:
              - 'libs/db-handler/**'
      - name: Test reports API
        if: steps.changes.outputs.reports-api == 'false'
        run: |
          cd ${GITHUB_WORKSPACE}/reports
          poetry --no-root install
          poetry run pytest
      - name: Test db-handler
        if: steps.changes.outputs.db-handler == 'true'
        run: |
          echo ${GITHUB_WORKSPACE}
          cd ${GITHUB_WORKSPACE}/libs/db-handler
          poetry --no-root install
          poetry run pytest
