name: Tests
on:
  pull_request:
    branches:
      - main
    paths:
      - 'libs/**'
      - 'reports/**'

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      reports-api: ${{ steps.changes.outputs.reports-api }}
      db-handler: ${{ steps.changes.outputs.db-handler }}
    steps:
      - name: Detect changes
        uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            reports-api:
              - 'reports/**'
              - 'libs/**'
            db-handler:
              - 'libs/db-handler/**'
  lint:
    needs: detect-changes
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install flake8
        run: pip install flake8
      - name: Lint with flake8 for db-handler
        if: needs.detect-changes.outputs.db-handler == 'true'
        run: |
          cd ${GITHUB_WORKSPACE}/libs/db-handler/db_handler
          flake8 . --count --statistics --show-source --max-complexity=10 --max-line-length=127
      - name: Lint with flake8 for reports API
        if: needs.detect-changes.outputs.reports-api == 'true'
        run: |
          cd ${GITHUB_WORKSPACE}/reports/reports
          flake8 . --count --statistics --show-source --max-complexity=10 --max-line-length=127
  tests:
    needs: detect-changes
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Set up Poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: '1.3.1'
      - name: Test db-handler
        if: needs.detect-changes.outputs.db-handler == 'true'
        run: |
          cd ${GITHUB_WORKSPACE}/libs/db-handler
          poetry --no-root install
          poetry run pytest'
      - name: Test reports API
        if: needs.detect-changes.outputs.reports-api == 'true'
        run: |
          cd ${GITHUB_WORKSPACE}/reports
          poetry --no-root install
          poetry run pytest
