name: Run tests
on:
  pull_request:
    branches:
      - main

jobs:
  detect-changes:
    uses: ./.github/workflows/detect-changes.yml
  db-library:
    needs: detect-changes
    if: needs.detect-changes.outputs.db-lib == 'true'
    uses: ./.github/workflows/test-template.yml
    with:
      base: libs/db-handler
      src: db_handler
  query-library:
    needs: detect-changes
    if: needs.detect-changes.outputs.query-lib == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Set up Poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: '1.3.1'
      - name: Install dependencies
        run: |
          cd ${GITHUB_WORKSPACE}/libs/query
          poetry --no-root install
      - name: Lint with black
        run: |
          poetry run black --check query
      - name: Test with pytest
        run: |
          poetry run pytest
  reports-api:
    needs: detect-changes
    if: needs.detect-changes.outputs.reports-api == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Set up Poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: '1.3.1'
      - name: Install dependencies
        run: |
          cd ${GITHUB_WORKSPACE}/reports
          poetry --no-root install
      - name: Lint with black
        run: |
          poetry run black --check reports
      - name: Test with pytest
        run: |
          poetry run pytest
