name: Template for test running
on:
  workflow_call:
    inputs:
      base:  # Base folder wrt respect to repo root
        required: true
        type: str
      src:  # Source folder wrt to base folder
        required: true
        type: str

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Set up Poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: '1.3.1'
      - name: Install dependencies
        run: |
          cd ${GITHUB_WORKSPACE}/${{ inputs.base }}
          poetry --no-root install
      - name: Lint with black
        run: poetry run black --check ${{ inputs.src }}
      - name: Test with pytest
        run: poetry run pytest
